sudo: required
dist: trusty
language: C


services:
  - docker

before install:
  - openssl aes-256-cbc -K $encrypted_7a7b4fe22176_key -iv $encrypted_7a7b4fe22176_iv -in mapotron.pem.enc -out ~/.ssh/mapotron.pem -d
  - chmod 600 ~/.ssh/mapotron.pem
  - ssh-add ~/.ssh/mapotron.pem
  - sudo mkdir -p /data
  
script:
  - sudo cp -R app/data/ /data
  - make build
  - docker run -v /data:/host/data -d -p 80:80 mapotron
  - sleep 60
  - docker run mapotron cat /var/log/shiny-server/shiny-server.log

after_success:
  - echo "SUCCESS"
  - git remote add dokku dokku@mapotron.org:mapotron
  - git push dokku master

notifications:
  email:
    on_success: change
    on_failure: change
