sudo: required
dist: trusty
language: C

services:
  - docker

before install:
  - openssl aes-256-cbc -K $encrypted_7a7b4fe22176_key -iv $encrypted_7a7b4fe22176_iv -in mapotron.enc -out mapotron -d
  - mkdir -p ~/.ssh
  - cp mapotron ~/.ssh/mapotron
  - chmod 600 ~/.ssh/mapotron
  - sudo mkdir -p /data
  
script:
  - sudo cp -R app/data/ /data
  - make build
  - make run
  - sleep 60
  - docker run mapotron cat /var/log/shiny-server/shiny-server.log

after_success:
  - echo "SUCCESS"
  - git push dokku master

notifications:
  email:
    on_success: change
    on_failure: change
