sudo: required
dist: trusty
language: C

services:
  - docker

before install:
  - sudo mkdir -p /data
  
script:
  - cp -R app/data /data
  - make all

after_success:
  - echo "SUCCESS" # TODO upload to production server

notifications:
  email:
    on_success: change
    on_failure: change
