sudo: required
dist: trusty
language: C

services:
  - docker

before_install:
  - git fetch --unshallow
  - openssl aes-256-cbc -K $encrypted_7a7b4fe22176_key -iv $encrypted_7a7b4fe22176_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv mapotron.pem ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan mapotron.org >> ~/.ssh/known_hosts
  - mv email.toml app/parameters/email.toml
  - sudo mkdir -p /data
  
script:
  - sudo cp -R app/data/ /data
  - make build
  - make run
  - sleep 60
  - make log

after_success:
  - echo "SUCCESS"
  - git remote add dokku dokku@mapotron.org:mapotron.org
  - sed -i 's/email.toml//g' .gitignore 
  - git commit -am "update"
  - git push dokku master

notifications:
  email:
    on_success: change
    on_failure: change
