install.packages(c("devtools","shiny","rgdal","Hmisc","RColorBrewer","plyr","RCurl","RJSONIO","taRifx.geo"))
library(devtools)
devtools::install_github('trestletech/ShinyDash')
devtools::install_github('paleo13/leaflet-shiny')
devtools::install_github('ebailey78/shinyBS')
devtools::install_github("rpremraj/mailR")
devtools::install_github("hadley/devtools")
